### PR TITLE
fix empty file error + add tests

### PR DESCRIPTION
**Pull request by jhoak**
Fix for #39 

Manual test and unit tests passed locally.

### CODE REVIEW

**Comment by gfs** [comment]
@daalcant can you ensure the pipelines are working before merge?

**Comment by gfs** [comment]
Thanks @jhoak.  LGTM. I will merge (and update DevSkim) once the pipelines are running and we get a unit test run.

**Comment by daalcant** [comment]
Appreciate the heads up here. Fixed a config issue and everything appears to be running again.

**Pull request merged**
