### PR TITLE
fix extracting 7zip files in parallel

### PR DESCRIPTION
**Pull request by svenclaesson**
the current version throws concurrent modification exception

### CODE REVIEW

**Comment by svenclaesson** [comment]
tree image is from https://commons.wikimedia.org/

**Comment by gfs** [comment]
I went through and added the new test case to (I think) everywhere we test all the archives, and also added a citation per the wikimedia page for the image you used for test data in the archive (directly in the archive, thus it is now 101 files, with 100 tree images).

**Comment by gfs** [comment]
Thanks again for the contribution @svenclaesson

**Comment by gfs** [comment]
I think it makes sense just to remove like I did for the other non-threadsafe implementations. I’ll can take care of it shortly.

**Comment by gfs** [comment]
PR is up to remove the 7z parallelized implementation and fix your other reported issue with iso batch sizes.

**Comment by gfs** [comment]
I am now considering refactoring the parallel implementation to operate at the Top-Level (when recursing) to sidestep any threadsafety issues with underlying threads #113.

**Pull request merged**
