### PR TITLE
Update SharpCompress to 0.36.

### PR DESCRIPTION
**Pull request by andreas-eriksson**
https://github.com/adamhathcock/sharpcompress/releases/tag/0.36.0

### CODE REVIEW

**Comment by gfs** [comment]
@andreas-eriksson I have incorporated this dependency update into #145, which also has fixes for the pipelines. That PR is waiting on a fix I submitted to be included in a new discutils package. I anticipate that will be available by early next week but if not I'll backport the pipeline changes here to merge this first.

**Comment by gfs** [comment]
This was incorporated in #145 and is now merged.

**Comment by andreas-eriksson** [comment]
Will there be a new release soon?

**Comment by gfs** [comment]
There should have been one yesterday after the merge, I'll look into any publishing issue today. Thanks for pointing it out.

**Pull request closed without merging**
