### PR TITLE
Also fix invalid filename chars separately from invalid path chars

### PR DESCRIPTION
**Pull request by gfs**
Also cover case of ExtractDirectory with parallel.

Follow up to fix more cases from #89.

### CODE REVIEW

**Comment by SteAmeR** [comment]
Sorry, but it doesn't work :\ . Colon ":" problem still persists.
last

**Comment by SteAmeR** [comment]
I wonder when Commit be ready? :)

**Comment by gfs** [comment]
@SteAmeR I just pushed a new commit.

**Comment by gfs** [comment]
Issue with the last commit. Path.GetFileName get confused by ':' and assumes that is a filename separator.

**Comment by gfs** [comment]
I refactored the latest to add a sanitized method to the fileentry so the behavior is testable and added a test case for your scenario - a Path that contains :.  For some reason, Path.InvalidPathChars does not prohibit :, even though that is not allowed on windows, so I've switch to Path.InvalidFileChars, but I first have to split the path by pieces, or else it replaces all the regular path separators as well.

**Comment by gfs** [comment]
@SteAmeR Sorry for the false start with the earlier fix and thanks for your patience. I think this one will do it.

**Comment by SteAmeR** [comment]
Thank you for all your effort, this was valuable fixes for the project.

**Pull request merged**
